server:
  port: ${appPort:8100}

# Actuator endpoint path (/admin/info, /admin/health, ...)
management.context-path: /admin

# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

info:
  app:
    name: @project.artifactId@
  build:
    version: @project.version@

spring:
  cloud:
    bus:
      enabled: false
    config:
      server:
        git :
          uri: https://github.com/edgardo1230/cloud-config
 
logging:
  file: ./logs/configServer.log
  level:
    org.springframework: WARN
    org.hibernate: ERROR
    com.raziem.config: INFO
    
    
---
spring:
  profiles: registration-first
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: ${hostName}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

---
spring:
  profiles: config-monitor
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: 192.168.56.210
    port: 5672
   